# # # # devconfig.yaml in your web_test_app directory
server:
# # # Custom HTTP Request Headers to inject
  headers:
    - name: "X-Custom_Header"
      value: "MyDevAppValue"
    - name: "Cache-Control"
      value: "no-cache, no-store, must-revalidate"

# # #   # Host and Port for the development server
# #   # host: 192.0.0.2  # Listen on all network interfaces (for testing from other devices)
  port: 7070    # A custom port

# #   # HTTPS Configuration (requires certificate and key files)
# #   # For testing, you can generate self-signed certs or omit this section initially.
# #   # To generate self-signed certs (for testing only):
# #   # openssl req -x509 -newkey rsa:2048 -nodes -keyout key.pem -out cert.pem -days 365
# #   # Fill in the prompts. Make sure key.pem and cert.pem are in the web_test_app directory.
# #   # https:
# #   #   cert-path: hello.local.key.pem
# #   #   cert-key-path: null

  proxy:
    #Source without rewrite
    #Must be above for /api/users/123 to match with this and not the one below
    - target: http://localhost:3000/
      prefix: /api
      headers: 
      - name: "X-Custom_Header"
        value: "MyDevAppValue"
    
    #Regex without replace
    - target: https://jsonplaceholder.typicode.com
      regex: '/users/(\d+)$'
    
    #Source with rewrite.
    - target: 'http://localhost:8080/'
      prefix: /dart
      replace: ""

    #rewriting with remainder. Regex with Replace. Add ^ to front of regex to prevent /people/users from matching
    - target: http://localhost:8080/ 
      regex: /users/(\d+)/profile
      replace: /users/info